#include <stdio.h>
#include <stdlib.h>
#include "Util/symbol_table.h"
#include "Util/statements_list.h"
#include "Step2/code_generator.h"

/* Declared in lex.yy.c */
void init_lexer(const char *filename);
int  yylex_destroy(void);
extern FILE *yyin;

/* Declared in parser_tab.c (generated by Bison) */
int yyparse(void);

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source.asm>\n", argv[0]);
        return EXIT_FAILURE;
    }

    init_symbol_table();
    init_statements_list();
    init_lexer(argv[1]);

    if (yyparse() != 0) {
        fprintf(stderr, "Parse error — aborting.\n");
        return EXIT_FAILURE;
    }

    generate_code();

    delete_statements_list();
    delete_symbol_table();
    fclose(yyin);
    yylex_destroy();

    return EXIT_SUCCESS;
}
