#include <stdio.h>
#include <stdlib.h>

#include "Util/symbol_table.h"
#include "Util/statements_list.h"
#include "Step2/code_generator.h"

/* Declared in lex_yy.c */
void init_lexer(const char *filename);

/* Declared in parser_tab.c (generated by Bison) */
int yyparse(void);

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source.asm>\n", argv[0]);
        return EXIT_FAILURE;
    }

    /* --- Pass 1: lex + parse → fill symbol table + statements list --- */
    init_symbol_table();
    init_statements_list();
    init_lexer(argv[1]);

    if (yyparse() != 0) {
        fprintf(stderr, "Parse error — aborting.\n");
        return EXIT_FAILURE;
    }

    /* --- Pass 2: walk statements list → emit hex object code --- */
    generate_code();

    /* Cleanup */
    delete_statements_list();
    delete_symbol_table();

    return EXIT_SUCCESS;
}
