#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 18 18:26:09 WET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_controller_time_synth -key {Post-Synthesis:sim_1:Timing:tb_controller} -tclbatch tb_controller.tcl -view /home/mendes/VGA_cararter_display/wcfg/tb_controller_behav.wcfg -log simulate.log"
xsim tb_controller_time_synth -key {Post-Synthesis:sim_1:Timing:tb_controller} -tclbatch tb_controller.tcl -view /home/mendes/VGA_cararter_display/wcfg/tb_controller_behav.wcfg -log simulate.log

