# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mariana/Desktop/project_2nd_Semester/processor/VGA_cararter_display.srcs/sources_1/ip/font_rom/font_rom.xci
# IP: The module: 'font_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mariana/Desktop/project_2nd_Semester/processor/VGA_cararter_display.gen/sources_1/ip/font_rom/font_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'font_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mariana/Desktop/project_2nd_Semester/processor/VGA_cararter_display.srcs/sources_1/ip/font_rom/font_rom.xci
# IP: The module: 'font_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mariana/Desktop/project_2nd_Semester/processor/VGA_cararter_display.gen/sources_1/ip/font_rom/font_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'font_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
