#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 17 17:05:07 WET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_vga_behav -key {Behavioral:sim_1:Functional:tb_vga} -tclbatch tb_vga.tcl -protoinst "protoinst_files/bd_654d.protoinst" -protoinst "protoinst_files/bd_ead3.protoinst" -protoinst "protoinst_files/vga_system.protoinst" -view /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/tb_vga.wcfg -log simulate.log"
xsim tb_vga_behav -key {Behavioral:sim_1:Functional:tb_vga} -tclbatch tb_vga.tcl -protoinst "protoinst_files/bd_654d.protoinst" -protoinst "protoinst_files/bd_ead3.protoinst" -protoinst "protoinst_files/vga_system.protoinst" -view /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/tb_vga.wcfg -log simulate.log

