# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.runs/synth_1/controller.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 5
set_msg_config  -id {Synth 37-125}  -string {{WARNING: [Synth 37-125] [ASSIGN-10]Some bits in IO 'i_ctrl' are not read. First unread bit index is 18. 
RTL Name 'i_ctrl', Hierarchy 'ctrl_dec', File 'ctrl_dec.v', Line 10.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.cache/wt [current_project]
set_property parent.project_path /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.2 [current_project]
set_property ip_output_repo /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/new/hsync_module.v
  /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/new/periph_vga.v
  /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/hdl/vga_system_wrapper.v
  /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/new/vsync_module.v
  /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/new/controller.v
}
add_files /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/bd/vga_system/vga_system.bd
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_processing_system7_0_0/vga_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_vdma_0_0/vga_system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_vdma_0_0/vga_system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_vdma_0_0/vga_system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_1/bd_654d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_5/bd_654d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_6/bd_654d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_7/bd_654d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_8/bd_654d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_9/bd_654d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_10/bd_654d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/bd_0/ip/ip_11/bd_654d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_rst_ps7_0_50M_0/vga_system_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_clk_wiz_0_1/vga_system_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_clk_wiz_0_1/vga_system_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_clk_wiz_0_1/vga_system_clk_wiz_0_1_late.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_clk_wiz_0_1/vga_system_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/bd_0/ip/ip_1/bd_ead3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/bd_0/ip/ip_5/bd_ead3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/bd_0/ip/ip_6/bd_ead3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/bd_0/ip/ip_7/bd_ead3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/bd_0/ip/ip_8/bd_ead3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/ip/vga_system_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/bd/vga_system/vga_system_ooc.xdc]

read_ip -quiet /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/mariana/Desktop/Peripherals/VGA_img/vgaIMG/vgaIMG.srcs/utils_1/imports/synth_1/vga_system_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top controller -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef controller.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file controller_utilization_synth.rpt -pb controller_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
