; ============================================================
; Generated by codegen  —  examples/demo.c
; Custom 16-bit RISC ISA
; ============================================================

; ── Global data ──────────────────────────────────────────
; extern @g  (resolved at link time)
; extern @h  (resolved at link time)

use_point:
    ; Frame slots (fp-based):
    ;   %slot5 (b) @ fp-6
    ;   %slot4 (a) @ fp-5
    ;   %slot2 (p) @ fp-3
    ;   %slot1 (py) @ fp-2
    ;   %slot0 (px) @ fp-1

    ; --- Prologue (leaf: skip lr save) ---
    PUSH(fp) 
    MOV(fp, sp) 
    ; Allocate 6 local slot(s)
    ADDI sp, sp, #-6

bb0:
    ADDI t0, fp, #-1
    SW a0, t0, #0
    ADDI t0, fp, #-2
    SW a1, t0, #0
    ADDI t0, fp, #-3
    MOV(t1, t0)
    ADD t1, r0
    ADDI t0, fp, #-1
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-3
    ADDI t3, r0, #1
    MOV(t1, t0)
    ADD t1, t3
    ADDI t0, fp, #-2
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t1, fp, #-5
    ADDI t0, fp, #-3
    ADD t0, r0
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t1, fp, #-6
    ADDI t0, fp, #-3
    ADDI t3, r0, #1
    ADD t0, t3
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-5
    LW t1, t0, #0
    ADDI t0, fp, #-6
    LW t0, t0, #0
    MOV(a0, t1)
    ADD a0, t0
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 6 local slot(s)
    ADDI sp, sp, #6
    POP(fp) 
    RET

bb1:
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 6 local slot(s)
    ADDI sp, sp, #6
    POP(fp) 
    RET


sum_corners:
    ; Frame slots (fp-based):
    ;   %slot4 (mat) @ fp-5
    ;   %slot3 (d) @ fp-4
    ;   %slot2 (c) @ fp-3
    ;   %slot1 (b) @ fp-2
    ;   %slot0 (a) @ fp-1

    ; --- Prologue (leaf: skip lr save) ---
    PUSH(fp) 
    MOV(fp, sp) 
    ; Allocate 8 local slot(s)
    ADDI sp, sp, #-8
    LW t3, fp, #1         ; load stack param d
    SW t3, fp, #-4         ; store to slot d

bb0:
    ADDI t0, fp, #-1
    SW a0, t0, #0
    ADDI t0, fp, #-2
    SW a1, t0, #0
    ADDI t0, fp, #-3
    SW a2, t0, #0
    ADDI t0, fp, #-5
    MOV(t0, r0)
    SLL(t0)
    ADD t0, t0
    MOV(t1, t0)
    ADD t1, r0
    ADDI t0, fp, #-1
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-5
    MOV(t0, r0)
    SLL(t0)
    ADD t0, t0
    ADDI t3, r0, #1
    MOV(t1, t0)
    ADD t1, t3
    ADDI t0, fp, #-2
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-5
    ADDI t3, r0, #1
    MOV(t0, t3)
    SLL(t0)
    ADD t0, t0
    MOV(t1, t0)
    ADD t1, r0
    ADDI t0, fp, #-3
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-5
    ADDI t3, r0, #1
    MOV(t0, t3)
    SLL(t0)
    ADD t0, t0
    ADDI t3, r0, #1
    MOV(t1, t0)
    ADD t1, t3
    ADDI t0, fp, #-4
    LW t0, t0, #0
    SW t0, t1, #0
    ADDI t0, fp, #-5
    MOV(t0, r0)
    SLL(t0)
    ADD t0, t0
    ADD t0, r0
    LW t1, t0, #0
    ADDI t0, fp, #-5
    ADDI t3, r0, #1
    MOV(t0, t3)
    SLL(t0)
    ADD t0, t0
    ADDI t3, r0, #1
    ADD t0, t3
    LW t0, t0, #0
    MOV(a0, t1)
    ADD a0, t0
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 8 local slot(s)
    ADDI sp, sp, #7
    ADDI sp, sp, #1
    POP(fp) 
    RET

bb1:
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 8 local slot(s)
    ADDI sp, sp, #7
    ADDI sp, sp, #1
    POP(fp) 
    RET


five_args:
    ; Frame slots (fp-based):
    ;   %slot4 (e) @ fp-5
    ;   %slot3 (d) @ fp-4
    ;   %slot2 (c) @ fp-3
    ;   %slot1 (b) @ fp-2
    ;   %slot0 (a) @ fp-1

    ; --- Prologue (leaf: skip lr save) ---
    PUSH(fp) 
    MOV(fp, sp) 
    ; Allocate 5 local slot(s)
    ADDI sp, sp, #-5
    LW t3, fp, #1         ; load stack param d
    SW t3, fp, #-4         ; store to slot d
    LW t3, fp, #2         ; load stack param e
    SW t3, fp, #-5         ; store to slot e

bb0:
    ADDI t0, fp, #-1
    SW a0, t0, #0
    ADDI t0, fp, #-2
    SW a1, t0, #0
    ADDI t0, fp, #-3
    SW a2, t0, #0
    ADDI t0, fp, #-1
    LW t1, t0, #0
    ADDI t0, fp, #-2
    LW t0, t0, #0
    ADD t1, t0
    ADDI t0, fp, #-3
    LW t0, t0, #0
    ADD t1, t0
    ADDI t0, fp, #-4
    LW t0, t0, #0
    ADD t1, t0
    ADDI t0, fp, #-5
    LW t0, t0, #0
    MOV(a0, t1)
    ADD a0, t0
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET

bb1:
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET


nested_calls:
    ; Frame slots (fp-based):
    ;   %slot1 (y) @ fp-3
    ;   %slot0 (x) @ fp-2

    ; --- Prologue ---
    PUSH(fp) 
    MOV(fp, sp) 
    PUSH(lr) 
    ; Allocate 2 local slot(s)
    ADDI sp, sp, #-2

bb0:
    ADDI t0, fp, #-2
    SW a0, t0, #0
    ADDI t0, fp, #-3
    SW a1, t0, #0
    ADDI t0, fp, #-2
    LW t1, t0, #0
    ADDI t0, fp, #-3
    LW a1, t0, #0
    MOV(a0, t1)
    CALL(h)
    ADDI t0, fp, #-3
    LW a1, t0, #0
    CALL(g)
    ; --- Epilogue ---
    ; Free 2 local slot(s)
    ADDI sp, sp, #2
    POP(lr) 
    POP(fp) 
    RET

bb1:
    ; --- Epilogue ---
    ; Free 2 local slot(s)
    ADDI sp, sp, #2
    POP(lr) 
    POP(fp) 
    RET


signed_div:
    ; Frame slots (fp-based):
    ;   %slot1 (b) @ fp-3
    ;   %slot0 (a) @ fp-2

    ; --- Prologue ---
    PUSH(fp) 
    MOV(fp, sp) 
    PUSH(lr) 
    ; Allocate 2 local slot(s)
    ADDI sp, sp, #-2

bb0:
    ADDI t0, fp, #-2
    SW a0, t0, #0
    ADDI t0, fp, #-3
    SW a1, t0, #0
    ADDI t0, fp, #-2
    LW t1, t0, #0
    ADDI t0, fp, #-3
    LW a1, t0, #0
    MOV(a0, t1)
    CALL(__divs)
    ; --- Epilogue ---
    ; Free 2 local slot(s)
    ADDI sp, sp, #2
    POP(lr) 
    POP(fp) 
    RET

bb1:
    ; --- Epilogue ---
    ; Free 2 local slot(s)
    ADDI sp, sp, #2
    POP(lr) 
    POP(fp) 
    RET


unsigned_div:
    ; Frame slots (fp-based):
    ;   %slot2 (q) @ fp-5
    ;   %slot1 (b) @ fp-4
    ;   %slot0 (a) @ fp-3

    ; --- Prologue ---
    PUSH(fp) 
    MOV(fp, sp) 
    PUSH(lr) 
    PUSH(r8)
    ; Allocate 3 local slot(s)
    ADDI sp, sp, #-3

bb0:
    ADDI t0, fp, #-3
    SW a0, t0, #0
    ADDI t0, fp, #-4
    SW a1, t0, #0
    ADDI s0, fp, #-5
    ADDI t0, fp, #-3
    LW t1, t0, #0
    ADDI t0, fp, #-4
    LW a1, t0, #0
    MOV(a0, t1)
    CALL(__divs)
    SW a0, s0, #0
    ADDI t0, fp, #-5
    LW a0, t0, #0
    ; --- Epilogue ---
    ; Free 3 local slot(s)
    ADDI sp, sp, #3
    POP(r8)
    POP(lr) 
    POP(fp) 
    RET

bb1:
    ; --- Epilogue ---
    ; Free 3 local slot(s)
    ADDI sp, sp, #3
    POP(r8)
    POP(lr) 
    POP(fp) 
    RET


cond_logic:
    ; Frame slots (fp-based):
    ;   %slot4 (.lor) @ fp-5
    ;   %slot3 (.land) @ fp-4
    ;   %slot2 (c) @ fp-3
    ;   %slot1 (b) @ fp-2
    ;   %slot0 (a) @ fp-1

    ; --- Prologue (leaf: skip lr save) ---
    PUSH(fp) 
    MOV(fp, sp) 
    ; Allocate 5 local slot(s)
    ADDI sp, sp, #-5

bb0:
    ADDI t0, fp, #-1
    SW a0, t0, #0
    ADDI t0, fp, #-2
    SW a1, t0, #0
    ADDI t0, fp, #-3
    SW a2, t0, #0
    ADDI t0, fp, #-1
    LW t0, t0, #0
    CMP r0, t0
    ADDI t0, r0, #0      ; assume false
    BLT .cmp_true_0
    BR .cmp_done_0
.cmp_true_0:
    ADDI t0, r0, #1      ; condition true
.cmp_done_0:
    NEG(t0)                 ; i1 sign-extend: 1→-1
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_1
    BR .cmp_done_1
.cmp_false_1:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_1:
    CMP t0, r0
    BEQ bb3
    BR  bb1

bb1:
    ADDI t0, fp, #-2
    LW t0, t0, #0
    CMP r0, t0
    ADDI t0, r0, #0      ; assume false
    BLT .cmp_true_2
    BR .cmp_done_2
.cmp_true_2:
    ADDI t0, r0, #1      ; condition true
.cmp_done_2:
    NEG(t0)                 ; i1 sign-extend: 1→-1
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_3
    BR .cmp_done_3
.cmp_false_3:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_3:
    CMP t0, r0
    BEQ bb3
    BR  bb2

bb2:
    ADDI t0, fp, #-4
    ADDI t3, r0, #1
    SW t3, t0, #0
    BR bb4

bb3:
    ADDI t0, fp, #-4
    SW r0, t0, #0
    BR bb4

bb4:
    ADDI t0, fp, #-4
    LW t0, t0, #0
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_4
    BR .cmp_done_4
.cmp_false_4:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_4:
    CMP t0, r0
    BEQ bb6
    BR  bb5

bb5:
    ADDI t0, fp, #-1
    LW t1, t0, #0
    ADDI t0, fp, #-2
    LW t0, t0, #0
    MOV(a0, t1)
    ADD a0, t0
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET

bb6:
    ADDI t0, fp, #-1
    LW t0, t0, #0
    CMP t0, r0
    ADDI t0, r0, #0      ; assume false
    BLT .cmp_true_5
    BR .cmp_done_5
.cmp_true_5:
    ADDI t0, r0, #1      ; condition true
.cmp_done_5:
    NEG(t0)                 ; i1 sign-extend: 1→-1
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_6
    BR .cmp_done_6
.cmp_false_6:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_6:
    CMP t0, r0
    BEQ bb8
    BR  bb9

bb7:
    BR bb6

bb8:
    ADDI t0, fp, #-3
    LW t0, t0, #0
    ADDI t3, r0, #10
    CMP t3, t0
    ADDI t0, r0, #0      ; assume false
    BLT .cmp_true_7
    BR .cmp_done_7
.cmp_true_7:
    ADDI t0, r0, #1      ; condition true
.cmp_done_7:
    NEG(t0)                 ; i1 sign-extend: 1→-1
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_8
    BR .cmp_done_8
.cmp_false_8:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_8:
    CMP t0, r0
    BEQ bb10
    BR  bb9

bb9:
    ADDI t0, fp, #-5
    ADDI t3, r0, #1
    SW t3, t0, #0
    BR bb11

bb10:
    ADDI t0, fp, #-5
    SW r0, t0, #0
    BR bb11

bb11:
    ADDI t0, fp, #-5
    LW t0, t0, #0
    CMP r0, t0
    ADDI t0, r0, #1      ; assume true (!=)
    BEQ .cmp_false_9
    BR .cmp_done_9
.cmp_false_9:
    ADDI t0, r0, #0      ; equal → false
.cmp_done_9:
    CMP t0, r0
    BEQ bb13
    BR  bb12

bb12:
    ADDI t0, fp, #-3
    LW a0, t0, #0
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET

bb13:
    MOV(a0, r0)
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET

bb14:
    BR bb13

bb15:
    ; --- Epilogue (leaf: skip lr restore) ---
    ; Free 5 local slot(s)
    ADDI sp, sp, #5
    POP(fp) 
    RET


