# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/constraintsPins.xdc

# IP: ip/font_rom/font_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==font_rom || ORIG_REF_NAME==font_rom} -quiet] -quiet

# IP: ip/char_buffer_bram/char_buffer_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==char_buffer_bram || ORIG_REF_NAME==char_buffer_bram} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
